fix(setup-osuosl-ca): use pwsh on Windows to avoid Cygwin CRLF issue
The composite action used 'shell: bash' for all platforms. On windows
runners with Cygwin, GitHub Actions generates the temp script with
Windows CRLF line endings. Cygwin bash without '-o igncr'
treats the \r as a command name, resulting in exit code 127.

We switch to PowerShell on windows to use native tools instead of
Cygwin.
Fixes: https://github.com/OpenVoxProject/puppet-runtime/actions/runs/33179641401/job/98877289758

Error for future reference:
```
  # Replace any backslashes with forward slashes so that a Windows path
  # is usable from both POSIX and WIN32 contexts.
  osuosl_ca="${RUNNER_TEMP//\\//}/osuosl-ca.pem"

  printf 'Downloading Mozilla CA bundle to: %s\n' "${osuosl_ca}"

  curl -sSL https://curl.se/ca/cacert.pem -o "${osuosl_ca}"

  printf 'AWS_CA_BUNDLE=%s' "${osuosl_ca}" >>$GITHUB_ENV
  shell: C:\cygwin64\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    VANAGON_LOCATION: https://github.com/openvoxproject/vanagon#main
D:\a\_temp\dcb0f279-a648-4603-9fd7-75c1faa0e719.sh: line 4: $'\r': command not found
Error: Process completed with exit code 127.
```

Signed-off-by: Tim Meusel <tim@bastelfreak.de>